CREATE TABLE `open_wawj_fuli_apply` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `APPLY_ID` varchar(64) DEFAULT NULL COMMENT '申请单id',
  `EMPLOYEE_ID` varchar(50) DEFAULT NULL COMMENT '分贝员工ID',
  `EMPLOYEE_NAME` varchar(50) DEFAULT NULL COMMENT '员工姓名',
  `EMPLOYEE_PHONE` varchar(50) DEFAULT NULL COMMENT '员工手机号',
  `COMPANY_ID` varchar(50) DEFAULT NULL COMMENT '公司ID',
  `COMPANY_NAME` varchar(200) DEFAULT NULL COMMENT '公司名称',
  `THIRD_USER_ID` varchar(100) DEFAULT NULL COMMENT '第三方用户ID',
  `WORK_DATE` datetime DEFAULT NULL COMMENT '工作日',
  `APPLY_TIME` datetime DEFAULT NULL COMMENT '申请时间',
  `STATUS` int(1) DEFAULT -1 COMMENT '-1:初始值;0:已处理;1:已关闭',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `idx_open_wawj_fuli_apply_apply_id` (`APPLY_ID`) USING HASH,
  KEY `idx_open_wawj_fuli_apply_work_date` (`WORK_DATE`) USING HASH
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8mb4 COMMENT='我爱我家福利申请';

CREATE TABLE `open_wawj_accont_unit_conf` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ACCOUNT_UNIT_CODE` varchar(50) DEFAULT NULL COMMENT '核算单位编码',
  `ACCOUNT_UNIT_NAME` varchar(128) DEFAULT NULL COMMENT '核算单位名称',
  `INCORPORATED_COMPANY_CODE` varchar(50) DEFAULT NULL COMMENT '法人公司编码',
  `INCORPORATED_COMPANY_NAME` varchar(128) DEFAULT NULL COMMENT '法人公司名字',
  `CITY_COMPANY_CODE` varchar(50) DEFAULT NULL COMMENT '城市公司编码',
  `CITY_COMPANY_NAME` varchar(128) DEFAULT NULL COMMENT '城市公司名字',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8mb4 COMMENT='我爱我家核算单位配置';

CREATE TABLE `open_wawj_reimburse_type_fee_project_conf` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ORDER_CATEGORY_TYPE` int(4) DEFAULT NULL COMMENT '场景类型编码',
  `ORDER_CATEGORY_NAME` varchar(64) DEFAULT NULL COMMENT '场景类型名称',
  `REIMBURSE_FORM_TYPE_CODE` varchar(50) DEFAULT NULL COMMENT '报销单类型编码',
  `REIMBURSE_FORM_TYPE_NAME` varchar(128) DEFAULT NULL COMMENT '报销单类型名称',
  `REIMBURSE_TYPE_CODE` varchar(50) DEFAULT NULL COMMENT '报销类型编码',
  `REIMBURSE_TYPE_NAME` varchar(128) DEFAULT NULL COMMENT '报销类型名称',
  `FEE_PROJECT_CODE` varchar(50) DEFAULT NULL COMMENT '费用项目编码',
  `FEE_PROJECT_NAME` varchar(128) DEFAULT NULL COMMENT '费用项目名称',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8mb4 COMMENT='我爱我家报销类型及费用项目配置';

CREATE TABLE `open_wawj_business_type_conf` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `BUSINESS_TYPE_CODE` varchar(50) DEFAULT NULL COMMENT '业务类型编码',
  `BUSINESS_TYPE_NAME` varchar(128) DEFAULT NULL COMMENT '业务类型名称',
  `CITY_COMPANY_CODE` varchar(50) DEFAULT NULL COMMENT '城市公司编码',
  `CITY_COMPANY_NAME` varchar(128) DEFAULT NULL COMMENT '城市公司名字',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8mb4 COMMENT='我爱我家业务类型配置';

CREATE TABLE `open_wawj_costcenter_conf` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `DEPT_CODE` varchar(50) DEFAULT NULL COMMENT '部门编码',
  `DEPT_NAME` varchar(128) DEFAULT NULL COMMENT '部门描述',
  `PARENT_DEPT_NAME` varchar(50) DEFAULT NULL COMMENT '上级部门名称',
  `DEPT_TYPE` varchar(128) DEFAULT NULL COMMENT '部门类型',
  `DEPT_LEVEL` varchar(50) DEFAULT NULL COMMENT '部门级别',
  `COST_CENTER_CODE` varchar(128) DEFAULT NULL COMMENT '成本中心编码',
  `COST_CENTER_NAME` varchar(50) DEFAULT NULL COMMENT '成本中心名称',
  `COST_CENTER_DESC` varchar(128) DEFAULT NULL COMMENT '成本中心描述',
  `SUMMARY_DEPT_CODE` varchar(50) DEFAULT NULL COMMENT '汇总部门编码',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8mb4 COMMENT='我爱我家成本中心配置';

CREATE TABLE `open_wawj_bill_detail` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `BATCH_ID` varchar(64) DEFAULT NULL COMMENT '批次id',
  `MD5VALUE` varchar(64) DEFAULT NULL COMMENT '分组条件md5值',
  `COMPANY_CODE` varchar(50) DEFAULT NULL COMMENT '公司编码',
  `REPORT_DATE` varchar(50) DEFAULT NULL COMMENT '报销日期',
  `EMPLOYEE_CODE` varchar(50) DEFAULT NULL COMMENT '报销人',
  `INCORPORATED_COMPANY` varchar(50) DEFAULT NULL COMMENT '法人公司',
  `ACCOUNT_COMPANY_CODE` varchar(50) DEFAULT NULL COMMENT '核算单位',
  `DESCRIPTION` varchar(2000) DEFAULT '' COMMENT '头描述',
  `LINE_DESCRIPTION` varchar(2000) DEFAULT NULL COMMENT '行描述',
  `EXPENSE_TYPE_CODE` varchar(200) DEFAULT NULL COMMENT '报销类型编码',
  `EXPENSE_ITEM_CODE` varchar(200) DEFAULT NULL COMMENT '费用项目编码',
  `TAX_TYPE_CODE` varchar(10) DEFAULT '#' COMMENT '税费类型 ps:3%增值税-经营类-10',
  `REPORT_AMOUNT` decimal(20,2) DEFAULT NULL COMMENT '报销金额',
  `TAX_RATE` varchar(20) DEFAULT '#' COMMENT '税率',
  `TAX_AMOUNT` decimal(20,2) DEFAULT NULL COMMENT '税额',
  `DEPT_CODE` varchar(200) DEFAULT NULL COMMENT '部门编码',
  `SUMMARY_DEPT_CODE` varchar(50) DEFAULT NULL COMMENT '汇总部门编码',
  `DIMENSION2_CODE` varchar(200) DEFAULT '0' COMMENT '项目',
  `DIMENSION3_CODE` varchar(200) DEFAULT '0' COMMENT '门店',
  `DIMENSION4_CODE` varchar(200) DEFAULT NULL COMMENT '业务类型',
  `ORDER_CATEGORY_TYPE` int(4) DEFAULT NULL COMMENT '场景类型编码',
  `ORDER_CATEGORY_NAME` varchar(64) DEFAULT NULL COMMENT '场景类型名称',
  `ORDER_DATE` varchar(50) DEFAULT NULL COMMENT '订单日期',
  `ORDER_TYPE` int(4) DEFAULT NULL COMMENT '订单类型1:因公;2:因私',
  `ORDER_ID` varchar(64) DEFAULT NULL COMMENT '订单id',
  `SOURCE_ORDER_ID` varchar(64) DEFAULT NULL COMMENT '原始订单id',
  `TICKET_NO` varchar(64) DEFAULT NULL COMMENT '票号',
  `BILL_ID` varchar(64) DEFAULT NULL COMMENT '账单id',
  `BILL_NO` varchar(64) DEFAULT NULL COMMENT '账单编号',
  `BILL_DETAIL_ID` varchar(64) DEFAULT NULL COMMENT '账单明细id',
  `ATTRIBUTE1` varchar(200) DEFAULT '#' COMMENT '备用字段1',
  `ATTRIBUTE2` varchar(200) DEFAULT '#' COMMENT '备用字段2',
  `ATTRIBUTE3` varchar(200) DEFAULT '#' COMMENT '备用字段3',
  `ATTRIBUTE4` varchar(200) DEFAULT '#' COMMENT '备用字段4',
  `ATTRIBUTE5` varchar(200) DEFAULT '#' COMMENT '备用字段5',
  `ATTRIBUTE6` varchar(200) DEFAULT '#' COMMENT '备用字段6',
  `ATTRIBUTE7` varchar(200) DEFAULT '#' COMMENT '备用字段7',
  `ATTRIBUTE8` varchar(200) DEFAULT '#' COMMENT '备用字段8',
  `ATTRIBUTE9` varchar(200) DEFAULT '#' COMMENT '备用字段9',
  `ATTRIBUTE10` varchar(200) DEFAULT '#' COMMENT '备用字段10',
  `ATTRIBUTE11` varchar(200) DEFAULT '#' COMMENT '备用字段11',
  `ATTRIBUTE12` varchar(200) DEFAULT '#' COMMENT '备用字段12',
  `ATTRIBUTE13` varchar(200) DEFAULT '#' COMMENT '备用字段13',
  `ATTRIBUTE14` varchar(200) DEFAULT '#' COMMENT '备用字段14',
  `ATTRIBUTE15` varchar(200) DEFAULT '#' COMMENT '备用字段15',
  `ATTRIBUTE16` varchar(200) DEFAULT '#' COMMENT '备用字段16',
  `ATTRIBUTE17` varchar(200) DEFAULT '#' COMMENT '备用字段17',
  `ATTRIBUTE18` varchar(200) DEFAULT '#' COMMENT '备用字段18',
  `ATTRIBUTE19` varchar(200) DEFAULT '#' COMMENT '备用字段19',
  `ATTRIBUTE20` varchar(200) DEFAULT '#' COMMENT '备用字段20',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  KEY `idx_open_wawj_bill_detail_billno` (`BILL_NO`) USING HASH,
  KEY `idx_open_wawj_bill_detail_order_id` (`ORDER_ID`) USING HASH,
  KEY `idx_open_wawj_bill_detail_billdetail_id` (`BILL_DETAIL_ID`) USING HASH,
  KEY `idx_open_wawj_bill_detail_md5value` (`MD5VALUE`) USING HASH
) ENGINE = InnoDB AUTO_INCREMENT = 1000 DEFAULT CHARSET = utf8mb4 COMMENT = '我爱我家账单明细';

CREATE TABLE `open_wawj_bill_summary` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `BILL_NO` varchar(64) DEFAULT NULL COMMENT '账单编号',
  `BATCH_ID` varchar(64) DEFAULT NULL COMMENT '批次id',
  `MD5VALUE` varchar(64) DEFAULT NULL COMMENT '分组条件md5值',
  `BATCH_LINE_ID` int(10) DEFAULT NULL COMMENT '批次行id',
  `STATUS` int(1) DEFAULT -1 COMMENT '状态 -1:初始化;0:成功;1:失败',
  `RESP_MSG` varchar(512) DEFAULT NULL COMMENT '响应信息',
  `COMPANY_CODE` varchar(50) DEFAULT NULL COMMENT '公司编码',
  `REPORT_DATE` varchar(50) DEFAULT NULL COMMENT '报销日期',
  `EMPLOYEE_CODE` varchar(50) DEFAULT NULL COMMENT '报销人',
  `INCORPORATED_COMPANY` varchar(50) DEFAULT NULL COMMENT '法人公司',
  `ACCOUNT_COMPANY_CODE` varchar(50) DEFAULT NULL COMMENT '核算单位',
  `DESCRIPTION` varchar(2000) DEFAULT '' COMMENT '头描述',
  `LINE_DESCRIPTION` varchar(2000) DEFAULT NULL COMMENT '行描述',
  `EXPENSE_TYPE_CODE` varchar(200) DEFAULT NULL COMMENT '报销类型编码',
  `EXPENSE_ITEM_CODE` varchar(200) DEFAULT NULL COMMENT '费用项目编码',
  `TAX_TYPE_CODE` varchar(10) DEFAULT '#' COMMENT '税费类型 ps:3%增值税-经营类-10',
  `REPORT_AMOUNT` decimal(20,2) DEFAULT NULL COMMENT '报销金额',
  `TAX_RATE` varchar(20) DEFAULT '#' COMMENT '税率',
  `TAX_AMOUNT` decimal(20,2) DEFAULT NULL COMMENT '税额',
  `UNIT_CODE` varchar(200) DEFAULT NULL COMMENT '部门编码',
  `DIMENSION2_CODE` varchar(200) DEFAULT '0' COMMENT '项目',
  `DIMENSION3_CODE` varchar(200) DEFAULT '0' COMMENT '门店',
  `DIMENSION4_CODE` varchar(200) DEFAULT NULL COMMENT '业务类型',
  `PAYEE_CATEGORY` varchar(50) DEFAULT NULL COMMENT '收款对象',
  `PAYEE_CODE` varchar(50) DEFAULT NULL COMMENT '收款方代码',
  `ATTRIBUTE1` varchar(200) DEFAULT '#' COMMENT '备用字段1',
  `ATTRIBUTE2` varchar(200) DEFAULT '#' COMMENT '备用字段2',
  `ATTRIBUTE3` varchar(200) DEFAULT '#' COMMENT '备用字段3',
  `ATTRIBUTE4` varchar(200) DEFAULT '#' COMMENT '备用字段4',
  `ATTRIBUTE5` varchar(200) DEFAULT '#' COMMENT '备用字段5',
  `ATTRIBUTE6` varchar(200) DEFAULT '#' COMMENT '备用字段6',
  `ATTRIBUTE7` varchar(200) DEFAULT '#' COMMENT '备用字段7',
  `ATTRIBUTE8` varchar(200) DEFAULT '#' COMMENT '备用字段8',
  `ATTRIBUTE9` varchar(200) DEFAULT '#' COMMENT '备用字段9',
  `ATTRIBUTE10` varchar(200) DEFAULT '#' COMMENT '备用字段10',
  `ATTRIBUTE11` varchar(200) DEFAULT '#' COMMENT '备用字段11',
  `ATTRIBUTE12` varchar(200) DEFAULT '#' COMMENT '备用字段12',
  `ATTRIBUTE13` varchar(200) DEFAULT '#' COMMENT '备用字段13',
  `ATTRIBUTE14` varchar(200) DEFAULT '#' COMMENT '备用字段14',
  `ATTRIBUTE15` varchar(200) DEFAULT '#' COMMENT '备用字段15',
  `ATTRIBUTE16` varchar(200) DEFAULT '#' COMMENT '备用字段16',
  `ATTRIBUTE17` varchar(200) DEFAULT '#' COMMENT '备用字段17',
  `ATTRIBUTE18` varchar(200) DEFAULT '#' COMMENT '备用字段18',
  `ATTRIBUTE19` varchar(200) DEFAULT '#' COMMENT '备用字段19',
  `ATTRIBUTE20` varchar(200) DEFAULT '#' COMMENT '备用字段20',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  KEY `idx_open_wawj_bill_sumarry_batch_id` (`BATCH_ID`) USING HASH
) ENGINE = InnoDB AUTO_INCREMENT = 1000 DEFAULT CHARSET = utf8mb4 COMMENT = '我爱我家账单汇总表';

CREATE TABLE `open_bill_scene_sum_zywx` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `BILL_NO` varchar(64) NOT NULL COMMENT '账单编号',
  `ITEM_NO` varchar(32) DEFAULT NULL COMMENT '项目编号',
  `ITEM_NAME` varchar(32) DEFAULT NULL COMMENT '项目名称',
  `ORDER_CATEGORY` int(8) NOT NULL COMMENT '订单场景类型',
  `CUSTOMER_MANAGER` varchar(64) NOT NULL COMMENT '客户经理',
  `COMPANY_ID` varchar(64) NOT NULL COMMENT '公司Id',
  `TRAIN_REFUND_INSURANCE_SUM` decimal(10,2) DEFAULT NULL COMMENT '火车票退票改签费用',
  `TRAIN_SERVICE_FEE` decimal(10,2) DEFAULT NULL COMMENT '火车票服务费',
  `TRAIN_TICKET_PRICE` decimal(10,2) DEFAULT NULL COMMENT '火车票价',
  `HOTEL_TOTAL_PRICE` decimal(10,2) DEFAULT NULL COMMENT '酒店总费用',
  `AIR_TICKET_PRICE` decimal(10,2) DEFAULT NULL COMMENT '机票票价',
  `AIR_SERVICE_FEE` decimal(10,2) DEFAULT NULL COMMENT '机票服务费',
  `AIR_REFUND_INSURANCE_SUM` decimal(10,2) DEFAULT NULL COMMENT '机票退票改签费用',
  `DINNER_TOTAL_PRICE` decimal(10,2) DEFAULT NULL COMMENT '用餐+外卖的总费用',
  `CAR_TOTAL_PRICE` decimal(10,2) DEFAULT NULL COMMENT '用车总费用',
  `SHANSONG_TOTAL_PRICE` decimal(10,2) DEFAULT NULL COMMENT '闪送总费用',
  `SUM_TOTAL_PRICE` decimal(10,2) DEFAULT NULL COMMENT '各场景各项目合计总费用',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`Id`),
  KEY `idx_company_id` (`COMPANY_ID`) USING BTREE,
  KEY `idx_bill_no` (`BILL_NO`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='自由无限账单场景汇总表'

CREATE TABLE `open_bill_sum_zywx` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `BILL_NO` varchar(64) NOT NULL COMMENT '账单编号',
  `ITEM_NO` varchar(32) DEFAULT NULL COMMENT '项目编号',
  `ITEM_NAME` varchar(32) DEFAULT NULL COMMENT '项目名称',
  `CUSTOMER_MANAGER` varchar(64) NOT NULL COMMENT '客户经理',
  `COMPANY_ID` varchar(64) NOT NULL COMMENT '公司Id',
  `TRAIN_REFUND_INSURANCE_CHANGE_SUM` decimal(10,2) DEFAULT NULL COMMENT '火车票退票改签保险费用',
  `TRAIN_SERVICE_FEE` decimal(10,2) DEFAULT NULL COMMENT '火车票服务费',
  `TRAIN_TICKET_PRICE` decimal(10,2) DEFAULT NULL COMMENT '火车票价',
  `HOTEL_TOTAL_PRICE` decimal(10,2) DEFAULT NULL COMMENT '酒店总费用',
  `AIR_TICKET_PRICE` decimal(10,2) DEFAULT NULL COMMENT '机票票价',
  `AIR_SERVICE_FEE` decimal(10,2) DEFAULT NULL COMMENT '机票服务费',
  `AIR_REFUND_INSURANCE_CHANGE_SUM` decimal(10,2) DEFAULT NULL COMMENT '机票退票改签保险费用',
  `DINNER_TOTAL_PRICE` decimal(10,2) DEFAULT NULL COMMENT '用餐+外卖的总费用',
  `CAR_TOTAL_PRICE` decimal(10,2) DEFAULT NULL COMMENT '用车总费用',
  `SHANSONG_TOTAL_PRICE` decimal(10,2) DEFAULT NULL COMMENT '闪送总费用',
  `SUM_TOTAL_PRICE` decimal(10,2) DEFAULT NULL COMMENT '闪送总费用',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`Id`),
  KEY `idx_company_id` (`COMPANY_ID`) USING BTREE,
  KEY `idx_bill_no` (`BILL_NO`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='自由无限账单汇总表'

ALTER TABLE `th_bill_scene_sum_zywjx` COMMENT '自由无限账单分场景汇总表';
ALTER TABLE `th_bill_scene_sum_zywjx`  RENAME TO `open_bill_scene_sum_zywx`;
ALTER TABLE `th_bill_sum_zywjx` COMMENT '自由无限账单汇总表';
ALTER TABLE `th_bill_sum_zywjx`  RENAME TO `open_bill_sum_zywx`;
UPDATE  `open_msg_setup` SET `str_val1` = '{\"url\":\"http://open-plus.fenbeitong.com/openapi/customize/ziyouwuxian/bill/pushBill?companyId=%s&billNo=%s\"}' WHERE `id` = 76;
UPDATE `open_msg_setup` SET `str_val1` = '{\"admin\":\"宿晓蕾\",\"admin_email\":\"suxiaolei@prphoto.com.cn\",\"copy_email\":\"liuying@prphoto.com.cn\", \"subject_name\":\"自由无限（北京）国际影像有限公司\"}' WHERE `id` = 77
UPDATE `open_msg_setup` SET `str_val1` = '{\"url\":\"http://open-plus.fenbeitong.com/openapi/customize/dasheng/bill/saveAndPushData?companyId=%s&billNo=%s\"}' WHERE `id` = 68;
ALTER TABLE `open_bill_detail_record`
MODIFY COLUMN `ITEM_COST_ATTRIBUTION_NAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '项目费用归属名称' AFTER `ITEM_COST_ATTRIBUTION_ID`,
ADD COLUMN `ITEM_COST_ATTRIBUTION_CODE` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '项目费用归属编号' AFTER `ITEM_COST_ATTRIBUTION_NAME`;

ALTER TABLE `open_bill_scene_sum_zywx`
ADD COLUMN `ALTMAN_TOTAL_PRICE` decimal(10, 2) NULL COMMENT '万能订单总费用' AFTER `SHANSONG_TOTAL_PRICE`,
MODIFY COLUMN `SUM_TOTAL_PRICE` decimal(10, 2) NULL DEFAULT NULL COMMENT '各场景总费用' AFTER `SHANSONG_TOTAL_PRICE`;

ALTER TABLE `open_bill_sum_zywx`
ADD COLUMN `ALTMAN_TOTAL_PRICE` decimal(10, 2) NULL COMMENT '万能订单总费用' AFTER `SHANSONG_TOTAL_PRICE`,
MODIFY COLUMN `SUM_TOTAL_PRICE` decimal(10, 2) NULL DEFAULT NULL COMMENT '各场景总费用' AFTER `SHANSONG_TOTAL_PRICE`;

ALTER TABLE `open_bill_detail_record`
MODIFY COLUMN `CHANGE_FEE` decimal(10, 2) NULL DEFAULT NULL COMMENT '改签费' AFTER `ENDORSE_DIFF_FEE`,
ADD COLUMN `CHANGE_EXT_FEE` decimal(10, 2) NULL COMMENT '改签服务费' AFTER `CHANGE_FEE`;

ALTER TABLE open_bill_scene_sum_zywx ADD COLUMN MALL_TOTAL_PRICE DECIMAL ( 10, 2 ) DEFAULT NULL COMMENT '采购总费用';

ALTER TABLE open_bill_sum_zywx ADD COLUMN MALL_TOTAL_PRICE DECIMAL ( 10, 2 ) DEFAULT NULL COMMENT '采购总费用';
