nacos:
  config:
    data-id: openapi-plugin-beisen
    server-addr: mse-f92e27f2-nacos-ans.mse.aliyuncs.com:8848
    group: OPENAPI_PLUGIN
    namespace: @profile.name@

spring:
  application:
    name: openapi-plugin-beisen
  profiles:
    active: @profile.name@
  cache:
    type: redis
  jackson:
    property-naming-strategy: SNAKE_CASE
    default_property_inclusion: NON_NULL
    time-zone: GMT+8

vehicle:
  swift:
    enabled: false
  adaptive:
    enabled: true
