CREATE TABLE `open_company_bill_ext_config` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `COMPANY_ID` varchar(50) DEFAULT NULL COMMENT '公司ID',
  `COMPANY_NAME` varchar(200) DEFAULT NULL COMMENT '公司名称',
  `ADMIN_COMAPNY_ID` varchar(50) DEFAULT NULL COMMENT '管理员公司id',
  `ADMIN_ID` varchar(50) DEFAULT NULL COMMENT '管理员id',
  `TYPE` int(5) DEFAULT NULL COMMENT '场景类型',
  `TYPE_NAME` varchar(20) DEFAULT NULL COMMENT '场景名称',
  `REQUEST_METHOD` int(1) DEFAULT NULL COMMENT '请求方法 1:http;2:dubbo',
  `REQUEST_PARAM` varchar(1024) DEFAULT NULL COMMENT '请求参数',
  `ETL_CONFIG_ID` bigint(20) DEFAULT NULL COMMENT 'etl配置ID',
  `AFTER_PROCESSOR` varchar(128) DEFAULT NULL COMMENT '后置处理器',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  KEY `idx_company_bill_ext_config_company` (`COMPANY_ID`) USING HASH
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8mb4 COMMENT='公司账单扩展信息配置表';