CREATE TABLE `tb_wechat_token_conf` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `COMPANY_ID` varchar(50) DEFAULT NULL COMMENT '公司ID',
  `COMPANY_NAME` varchar(200) DEFAULT NULL COMMENT '公司名称',
  `REQUEST_METHOD` varchar(128) DEFAULT NULL COMMENT '请求方法',
  `REQUEST_URL` varchar(512) DEFAULT NULL COMMENT '请求地址',
  `REQUEST_BODY` varchar(1024) DEFAULT NULL COMMENT '请求体',
  `CLASS_NAME` varchar(256) DEFAULT NULL COMMENT '类名',
  `TOKEN_EXPRESS` varchar(256) DEFAULT NULL COMMENT 'token所在位置',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  KEY `idx_wechat_token_conf_company` (`COMPANY_ID`) USING HASH
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8mb4 COMMENT='微信token配置表';
